-- AlterTable
ALTER TABLE "news_data" ALTER COLUMN "company_rel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "insider_rel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "outsider_rel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ceo_rel" SET DATA TYPE DOUBLE PRECISION;
